services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  WapplerSystems\Pretix\:
    resource: '../Classes/*'

  WapplerSystems\Pretix\Service\ApiService:
    public: true
